
import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import  './styles/layout.css'

import StyledComponentsRegistry from './lib/registry'

import HomeLayout from './components/HomeLayout'
import Navbar from './components/Navbar/Navbar'

import NextAuthProvider from './NextAuthProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from './lib/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry >
          <NextAuthProvider session={session}>
            <Navbar />
            <HomeLayout >
              {children}
            </HomeLayout>
          </NextAuthProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
