import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import  './styles/layout.css'

import StyledComponentsRegistry from './lib/registry'

import HomeLayout from './components/HomeLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry >
          <HomeLayout >
          {children}
          </HomeLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
