'use client';

import Image from 'next/image';
import styles from './styles/Home.module.css';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import Head from 'next/head';
import { useSession } from 'next-auth/react';

export default function Home() {
  const router = useRouter();

  const { data: session, status } = useSession();

  console.log({session, status});


  const handleClick = () => {
    console.log('Your order placed!');
    router.push(`/product`);
    // router.replace(`/product`);
  };

  return (
    <div className={styles.container}>
      <h1>Home Page</h1>
      <Link href={'/blog'}>Blog</Link>
      <Link href={'/product'}>Products</Link>
      <button onClick={handleClick}>Place Order</button>
      <h1>Next JS Pre-rendering </h1>
      <Link href={'/users'} prefetch>
        Users
      </Link>
      <Link href={'/posts'} prefetch>
        Posts
      </Link>
      
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         {session? `${session.user?.name},` : ''} Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        
        <p className={styles.description}>
          Get started by editing{` `}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>

        </div>
      </main>

    </div>
    
  );
}
